name: Cypress Tests

on: [ push ]

permissions: write-all

jobs:

  cypress-run1:
    runs-on: ubuntu-latest
    timeout-minutes: 250
    container:
      image: cypress/browsers:node16.14.2-slim-chrome100-ff99-edge
      options: --user 1001

    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm i

      - name: Run tests
        run: npm run tests-org1

      - uses: actions/checkout@v2
      - name: copy
        if: always()
        env:
          SRC_FOLDER_PATH: 'report/allure-results'
          TARGET_BRANCH: 'gh-pages'
        run: |
          files=$(find $SRC_FOLDER_PATH -type f) # get the file list
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git config remote.origin.fetch '+refs/heads/*:refs/remotes/origin/*'
          git remote update
          git fetch --all --prune                         # fetch branches
          git checkout $TARGET_BRANCH       # checkout to your branch
          git checkout ${GITHUB_REF##*/} -- $files # copy files from the source branch
          git ls
          git status
          git add -f -A
          git diff-index --quiet HEAD ||  git commit -am "deploy files"  # commit to the repository (ignore if no modification)
          git push origin $TARGET_BRANCH # push to remote branch

  cypress-run2:
    runs-on: ubuntu-latest
    timeout-minutes: 250
    container:
      image: cypress/browsers:node16.14.2-slim-chrome100-ff99-edge
      options: --user 1001

    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm i

      - name: Run tests
        run: npm run tests-org2

      - uses: actions/checkout@v2
      - name: copy
        if: always()
        env:
          SRC_FOLDER_PATH: 'report/allure-results'
          TARGET_BRANCH: 'gh-pages'
        run: |
          files=$(find $SRC_FOLDER_PATH -type f) # get the file list
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git config remote.origin.fetch '+refs/heads/*:refs/remotes/origin/*'
          git remote update
          git fetch --all --prune                         # fetch branches
          git status
          git checkout $TARGET_BRANCH       # checkout to your branch
          git status
          git checkout ${GITHUB_REF##*/} -- $files # copy files from the source branch
          git ls
          git status
          git add -f -A
          git diff-index --quiet HEAD ||  git commit -am "deploy files"  # commit to the repository (ignore if no modification)
          git push origin $TARGET_BRANCH # push to remote branch


  report:
    runs-on: ubuntu-latest
    timeout-minutes: 250
    needs: [ cypress-run1, cypress-run2 ]
    if: always()
    container:
      image: cypress/browsers:node16.14.2-slim-chrome100-ff99-edge
      options: --user 1001

    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
        with:
          ref: gh-pages

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Generate Allure Report
        if: always()
        run: |
          node_modules/allure-commandline/dist/bin/allure generate  report/allure-results -o report/test

      - name: Host Report on GH pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: report/test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy report to Github Pages newman directory
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: report/test



