name: Cypress Tests

on: [ push ]

permissions: write-all

jobs:

  report:
    runs-on: ubuntu-22.04
    timeout-minutes: 250
    if: always()
    container:
      image: cypress/browsers:node16.14.2-slim-chrome100-ff99-edge
      options: --user 1001

    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
        with:
          ref: gh-pages

      - name: Install dependencies
        run: |
          npm init --yes
          npm i allure-commandline --save-dev

      - name: Merge allure-results-{org#} folders
        run: |
          cp -rl allure-results-1/ allure-results/
          cp -rl allure-results-2/ allure-results/
          rm -r allure-results-1
          rm -r allure-results-2

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Generate Allure Report
        if: always()
        run: |
          node_modules/allure-commandline/dist/bin/allure generate  allure-results -o report

      - name: Deploy report to Github Pages directory
        uses: peaceiris/actions-gh-pages@v2
        with:
          keepFiles: false
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: report



