name: Cypress Tests

on: [push]
permissions: write-all

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 250
    container:
      image: cypress/browsers:node16.14.2-slim-chrome100-ff99-edge
      options: --user 1001
    strategy:
      fail-fast: false
      matrix:
        include:
          - spec_group: src/specs/smoke/main-actions.js
            org_number: 1
          - spec_group: src/specs/smoke/services.js
            org_number: 2
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests in parallel
        run: npm run dev-smoke-test-parallel -- --spec ${{ matrix.spec_group }} --env environment=dev,orgNum=${{ matrix.org_number }}
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CI: true

      - name: Push report folder to external report-${{ matrix.org_number }} branch
        if: always()
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"

          REPORT_BRANCH=report-${{ matrix.org_number }}
          NOW=$(date +'%B_%d')

          git clone https://x-access-token:${{ secrets.TOKEN }}@github.com/Safe-QA/report_${NOW}.git external-repo
          cd external-repo

          if git ls-remote --heads origin $REPORT_BRANCH | grep $REPORT_BRANCH; then
            git checkout $REPORT_BRANCH
          else
            git checkout -b $REPORT_BRANCH
          fi

          rm -rf *

          cp -r ../report/allure-results-${{ matrix.org_number }}/* ./

          git add .
          git commit -m "Allure results for org-${{ matrix.org_number }}" || echo "No changes to commit"
          git push origin $REPORT_BRANCH

  merge-and-deploy-final-report:
    runs-on: ubuntu-latest
    timeout-minutes: 250
    needs: [cypress-tests]
    if: always()
    steps:
      - name: Set environment variable
        run: echo "NOW=$(date +'%B_%d')" >> $GITHUB_ENV

      - name: Clone and prepare gh-pages
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"

          git clone https://x-access-token:${{ secrets.TOKEN }}@github.com/Safe-QA/report_${NOW}.git merged-repo
          cd merged-repo
          git checkout gh-pages || git checkout -b gh-pages
          
          rm -rf *
          mkdir -p allure-results
          git add .
          git commit -m "Clean gh-pages before merging report branches" || echo "Nothing to commit"
          git push origin gh-pages

      - name: Merge report-1 directly into gh-pages
        run: |
          cd merged-repo
          git fetch origin report-1
          git checkout gh-pages

          # Merge report-1 into gh-pages, resolving conflicts by favoring changes from report-1
          git merge origin/report-1 --no-ff -m "Merge report-1 into gh-pages" || true

          # Handle conflicts manually by keeping files from report-1 (overwriting deletions)
          git checkout --theirs .
          git add .
          git commit -m "Resolve merge conflict by keeping report-1 files" || echo "No changes"

          git push origin gh-pages

      - name: Merge report-2 directly into gh-pages
        run: |
          cd merged-repo
          git fetch origin report-2
          git checkout gh-pages

          # Merge report-2 into gh-pages, resolving conflicts by favoring changes from report-2
          git merge origin/report-2 --no-ff -m "Merge report-2 into gh-pages" || true

          # Handle conflicts manually by keeping files from report-2 (overwriting deletions)
          git checkout --theirs .
          git add .
          git commit -m "Resolve merge conflict by keeping report-2 files" || echo "No changes"

          git push origin gh-pages

      - name: Install Allure CLI
        run: npm install -g allure-commandline

      - name: Generate Final Allure Report
        run: |
          # Ensure you're in the correct directory and on the gh-pages branch
          cd merged-repo

          # Checkout the gh-pages branch and pull the latest changes
          git checkout gh-pages
          git pull origin gh-pages

          # Verify you're in the correct directory and the gh-pages branch
          echo "Listing files in the current directory after checkout:"
          ls -l

          # Ensure allure-results directory exists
          mkdir -p allure-results

          # List files again to ensure .json files are present
          echo "Listing files again after ensuring allure-results exists:"
          ls -l

          # Move .json files to allure-results (if they exist)
          mv *.json allure-results/ || echo "No .json files to move"

          # Generate Allure report
          allure generate allure-results -o allure-report

          # Verify allure-report directory exists
          echo "Listing files after generating Allure report:"
          ls -l allure-report

      - name: Push Final Allure Report
        run: |
          cd merged-repo/allure-report
          git add .
          git commit -m "Final Allure Report generated from all org reports" || echo "No changes"
          git push origin gh-pages

  slack-notification:
    runs-on: ubuntu-latest
    needs: [cypress-tests, merge-and-deploy-final-report]
    if: always()
    steps:
      - name: Set date
        run: echo "NOW=$(date +'%B_%d')" >> $GITHUB_ENV

      - name: Send Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_MESSAGE: 'Report URL: https://safe-qa.github.io/report_${{ env.NOW }}'
          SLACK_TITLE: Cypress Test Results
          SLACK_USERNAME: Cypress_Tests
