name: Cypress Tests

on: [push]
permissions: write-all

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 250
    container:
      image: cypress/browsers:node16.14.2-slim-chrome100-ff99-edge
      options: --user 1001
    strategy:
      fail-fast: false
      matrix:
        include:
          - spec_group: src/specs/smoke/main-actions.js
            org_number: 1
          - spec_group: src/specs/smoke/services.js
            org_number: 2
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests in parallel
        run: npm run dev-smoke-test-parallel -- --spec ${{ matrix.spec_group }} --env environment=dev,orgNum=${{ matrix.org_number }}
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CI: true

      - name: Archive Allure Results (if exists)
        if: always()
        run: |
          if [ -d "allure-results" ]; then
            echo "Allure results found, archiving..."
            tar -czf allure-results-${{ matrix.org_number }}.tgz allure-results
          else
            echo "No Allure results found for org ${{ matrix.org_number }}"
            mkdir empty-dir && tar -czf allure-results-${{ matrix.org_number }}.tgz empty-dir
          fi

      - name: Upload Allure Artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: allure-results-${{ matrix.org_number }}
          path: allure-results-${{ matrix.org_number }}.tgz

  merge-and-deploy-final-report:
    runs-on: ubuntu-latest
    needs: [cypress-tests]
    if: always()
    steps:
      - uses: actions/checkout@v2

      - name: Set up environment variable
        id: set_date
        run: echo "NOW=$(date +'%B_%d')" >> $GITHUB_ENV

      - name: Download Allure Artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Install Java & Allure CLI
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Allure CLI
        run: |
          npm init -y
          npm install -D allure-commandline

      - name: Extract Allure Artifacts
        run: |
          mkdir -p allure-results
          for archive in artifacts/allure-results-*/allure-results-*.tgz; do
            echo "Extracting $archive..."
            tar -xzf "$archive" -C allure-results --strip-components=1 || true
          done

      - name: Generate Allure Report
        if: always()
        run: |
          node_modules/.bin/allure generate allure-results -o report || echo "No report generated"

      - name: Deploy to external repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.TOKEN }}
          NOW: ${{ env.NOW }}
        with:
          source-directory: report
          destination-github-username: 'Safe-QA'
          destination-repository-name: 'report_${{ env.NOW }}'
          user-email: 'qa+github1@trackerproducts.com'
          target-branch: "gh-pages"

  slack-notification:
    runs-on: ubuntu-latest
    needs: [cypress-tests, merge-and-deploy-final-report]
    if: always()
    steps:
      - name: Set up environment variable
        id: set_date
        run: echo "NOW=$(date +'%B_%d')" >> $GITHUB_ENV

      - name: Send Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_MESSAGE: 'Report URL: https://safe-qa.github.io/report_${{ env.NOW }}'
          SLACK_TITLE: Cypress Test Results
          SLACK_USERNAME: Cypress_Tests
