name: Cypress Tests

on: [push]
permissions: write-all

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 250
    container:
      image: cypress/browsers:node16.14.2-slim-chrome100-ff99-edge
      options: --user 1001
    strategy:
      fail-fast: false
      matrix:
        include:
          - spec_group: src/specs/smoke/main-actions.js
            org_number: 1
          - spec_group: src/specs/smoke/services.js
            org_number: 2
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests in parallel
        run: npm run dev-smoke-test-parallel -- --spec ${{ matrix.spec_group }} --env environment=dev,orgNum=${{ matrix.org_number }}
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CI: true

      - name: Push allure results to report-${{ matrix.org_number }} branch in external repo
        if: always()
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"

          mkdir temp-repo
          cd temp-repo
          git clone --depth 1 --branch gh-pages https://x-access-token:${{ secrets.TOKEN }}@github.com/Safe-QA/report_${{ github.run_id }}.git .
          git checkout -b report-${{ matrix.org_number }} || git checkout report-${{ matrix.org_number }}
          rm -rf ./*
          cp -r ../report/allure-results-${{ matrix.org_number }}/* . || echo "No results found"
          git add .
          git commit -m "Add report for org-${{ matrix.org_number }}" || echo "Nothing to commit"
          git push origin report-${{ matrix.org_number }}

  merge-and-deploy-final-report:
    runs-on: ubuntu-latest
    timeout-minutes: 250
    needs: [cypress-tests]
    if: always()
    steps:
      - name: Checkout external repo
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"

          git clone --branch gh-pages https://x-access-token:${{ secrets.TOKEN }}@github.com/Safe-QA/report_${{ github.run_id }}.git external-repo
          cd external-repo

          git fetch origin report-1
          git merge origin/report-1 --no-ff -m "Merge report-1 into gh-pages"

          git fetch origin report-2
          git merge origin/report-2 --no-ff -m "Merge report-2 into gh-pages"

          git push origin gh-pages

  slack-notification:
    runs-on: ubuntu-latest
    needs: [cypress-tests, merge-and-deploy-final-report]
    if: always()
    steps:
      - name: Set date
        run: echo "NOW=$(date +'%B_%d')" >> $GITHUB_ENV

      - name: Send Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_MESSAGE: 'Report URL: https://safe-qa.github.io/report_${{ github.run_id }}'
          SLACK_TITLE: Cypress Test Results
          SLACK_USERNAME: Cypress_Tests
