name: Cypress Tests

on: [ push ]

permissions: write-all

jobs:

  cypress-org1:
    runs-on: ubuntu-latest
    timeout-minutes: 250
    container:
      image: cypress/browsers:node16.14.2-slim-chrome100-ff99-edge
      options: --user 1001
    strategy:
      fail-fast: false
    steps:

      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm i
      - name: Run tests
        run: npm run tests-org1
      - name: Deploy report to temp-reports branch
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        with:
          keepFiles: true
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: report

    report:
        - uses: ./.github/workflows/push_report_to_eternal_repo.yml
