name: Cypress Tests

on: [push]
permissions: write-all

jobs:

  cypress-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 250
    container:
      image: cypress/browsers:node16.14.2-slim-chrome100-ff99-edge
      options: --user 1001
    strategy:
      fail-fast: false
      matrix:
        include:
          - spec_group: src/specs/smoke/main-actions.js
            org_number: 1
          - spec_group: src/specs/smoke/services.js
            org_number: 2
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests in parallel
        run: npm run dev-smoke-test -- --spec ${{ matrix.spec_group }} --env environment=dev,orgNum==${{ matrix.org_number }}
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CI: true

      - name: Clean gh-pages branch in this repository
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          git clone --branch gh-pages https://x-access-token:${{ secrets.TOKEN }}@github.com/${{ github.repository }}.git temp-gh-pages
          cd temp-gh-pages
          git rm -r * || echo "Nothing to delete"
          git commit -am "Clean gh-pages before redeploy"
          git push origin gh-pages
        if: always()

      - name: Deploy report to temp-reports branch
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        with:
          keepFiles: true
        env:
          PERSONAL_TOKEN: ${{ secrets.TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: report

  merge-and-deploy-final-report:
    runs-on: ubuntu-latest
    timeout-minutes: 250
    needs: [cypress-tests]
    if: always()
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
        with:
          ref: gh-pages

      - name: Install dependencies and move allure results
        run: |
          npm init --yes
          npm i allure-commandline --save-dev
          mkdir allure-results
          [ -d "allure-results-1" ] && mv allure-results-1/* allure-results || echo "No allure-results-1 directory"
          [ -d "allure-results-2" ] && mv allure-results-2/* allure-results || echo "No allure-results-2 directory"

      - name: Set up environment variable
        id: set_date
        run: echo "NOW=$(date +'%B_%d')" >> $GITHUB_ENV

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Generate Allure Report
        if: always()
        run: node_modules/allure-commandline/dist/bin/allure generate allure-results -o report

      - name: Deploy to external repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.TOKEN }}
          NOW: ${{ env.NOW }}
        with:
          source-directory: report
          destination-github-username: 'Safe-QA'
          destination-repository-name: 'report_${{ env.NOW }}'
          user-email: 'qa+github1@trackerproducts.com'
          target-branch: "gh-pages"

  slack-notification:
    runs-on: ubuntu-latest
    needs: [ cypress-tests, merge-and-deploy-final-report ]
    if: always()
    steps:
      - name: Set up environment variable
        id: set_date
        run: echo "NOW=$(date +'%B_%d')" >> $GITHUB_ENV

      - name: Send Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_MESSAGE: 'Report URL: https://safe-qa.github.io/report_${{ env.NOW }}'
          SLACK_TITLE: Cypress Test Results
          SLACK_USERNAME: Cypress_Tests
