name: Cypress Tests

on: [ push ]

permissions: write-all

jobs:

  cypress-run1:
    runs-on: ubuntu-latest
    timeout-minutes: 250
    container:
      image: cypress/browsers:node16.14.2-slim-chrome100-ff99-edge
      options: --user 1001

    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm i

      - name: Run tests
        run: npm run tests-org1

      - name: Install Allure
        if: always()
        run: |
          npm install allure-commandline --save-dev
          allure generate report/allure-results --clean -o allure-report

      


