name: Cypress Tests

on: [ push ]

permissions: write-all

jobs:

  cypress-run1:
    runs-on: ubuntu-latest
    timeout-minutes: 250
    container:
      image: cypress/browsers:node16.14.2-slim-chrome100-ff99-edge
      options: --user 1001

    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3

      - name: Install dependencies
        run: npm i

      - name: Run tests
        run: npm run tests-org1

      - name: Generate Allure Report
        if: always()
        run: |
          node_modules/allure-commandline/dist/bin/allure generate  report/allure-results -o report/test

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: dist/weather-app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}




