slack-notification:
  runs-on: ubuntu-latest
  needs: [cypress-org1, merge-and-deploy-final-report]
  if: always()  # Always send notification, even if previous jobs fail
  steps:
    - name: Send Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      with:
        slack_token: ${{ secrets.SLACK_BOT_TOKEN }}
        slack_channel: '#auto-test-reports'
        text: |
          :tada: **Cypress Test Workflow Status**
          - **Test Status**: ${{ job.status }}
          - **Repository**: ${{ github.repository }}
          - **Branch**: ${{ github.ref }}
          - **Commit**: ${{ github.sha }}
          - **Job**: ${{ job.name }}
          - **Run**: ${{ github.run_id }}
