name: Cypress Tests

on: [ push ]

permissions: write-all

jobs:
  cypress-run1:
    runs-on: ubuntu-latest
    timeout-minutes: 250
    container:
      image: cypress/browsers:node16.14.2-slim-chrome100-ff99-edge
      options: --user 1001

    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm i

      - name: Run tests
        run: npm run tests-org1

      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: report/allure-results
          allure_history: allure-history
          keep_reports: 2

  cypress-run2:
    runs-on: ubuntu-latest
    timeout-minutes: 250
    container:
      image: cypress/browsers:node16.14.2-slim-chrome100-ff99-edge
      options: --user 1001

    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm i

      - name: Run tests
        run: npm run tests-org2

      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: report/allure-results
          allure_history: allure-history
          keep_reports: 2

  deployReport:
    name: Deploy Report
    runs-on: ubuntu-latest
    if: always()
    needs: [ cypress-run1, cypress-run2 ]
    steps:
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history

  notify:
    name: Notify on Slack
    runs-on: ubuntu-latest
    if: always()
    needs: [ cypress-run ]

    steps:
      - uses: abinoda/slack-action@master
        env:
          SLACK_BOT_TOKEN: ${{secrets.SLACK_BOT_TOKEN }}
        with:
          # custom message to send to slack
          args: '{\"channel\":\"${{ secrets.SLACK_PR_CHANNEL_ID }}\",\"blocks\":[{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"*Automated test report* https://qa-github1.github.io/safe-web-test-automation/  \"}}]}'
